services:
  producer:
    build: ./producer
    ports:
      - "5000:5000"
    networks:
      - microservices_network
      - rabbitmq_network
  consumer_one:
    build: ./consumer_one
    networks:
      - microservices_network
      - rabbitmq_network
  consumer_two:
    build: ./consumer_two
    networks:
      - microservices_network
      - rabbitmq_network
  consumer_three:
    build: ./consumer_three
    networks:
      - microservices_network
      - rabbitmq_network
  consumer_four:
    build: ./consumer_four
    networks:
      - microservices_network
      - rabbitmq_network
  database:
    image: mongo:latest
    container_name: database
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ccproject
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    command: mongod --auth
    networks:
      - microservices_network
      - rabbitmq_network
networks:
  microservices_network:
    name: microservices_network
  rabbitmq_network:
    name: rabbitmq_network
