version: "3.8"

services:
  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    networks:
      - rabbitmq_network

  producer:
    build: ./producer
    ports:
      - "5672:5672"
    networks:
      - microservices_network
    depends_on:
      - rabbitmq

  consumer_one:
    build: ./consumer_one
    networks:
      - microservices_network
    depends_on:
      - rabbitmq

  consumer_two:
    build: ./consumer_one
    networks:
      - microservices_network
    depends_on:
      - rabbitmq

  consumer_three:
    build: ./consumer_one
    networks:
      - microservices_network
    depends_on:
      - rabbitmq

  consumer_four:
    build: ./consumer_one
    networks:
      - microservices_network
    depends_on:
      - rabbitmq

  database:
    image: mongo:latest
    container_name: database
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ccproject
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    command: mongod --auth
    networks:
      - microservices_network


networks:
  rabbitmq_network:
  microservices_network:
